spring:
  datasource:
    url: jdbc:h2:mem:sistema_tarefas;DB_CLOSE_DELAY=-1;MODE=DB2
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
